"""
Fortune 500 ticker registry (publicly traded companies only).
Quasi-government entities (Fannie Mae, Freddie Mac) excluded.
Private companies (Cargill, Koch) excluded.

Import:
    from ingestion.tickers import TICKERS, SECTOR_MAP
"""

# (ticker, sector)
_ALL: list[tuple[str, str]] = [
    # ── Technology ──────────────────────────────────────────────────────────
    ("AAPL",  "Technology"),
    ("MSFT",  "Technology"),
    ("GOOGL", "Technology"),
    ("META",  "Technology"),
    ("NVDA",  "Technology"),
    ("DELL",  "Technology"),
    ("HPQ",   "Technology"),
    ("IBM",   "Technology"),
    ("INTC",  "Technology"),
    ("CSCO",  "Technology"),
    ("ORCL",  "Technology"),
    ("AMD",   "Technology"),
    ("QCOM",  "Technology"),
    ("TXN",   "Technology"),
    ("AVGO",  "Technology"),
    ("AMAT",  "Technology"),
    ("LRCX",  "Technology"),
    ("KLAC",  "Technology"),
    ("MU",    "Technology"),
    ("ADBE",  "Technology"),
    ("CRM",   "Technology"),
    ("NOW",   "Technology"),
    ("INTU",  "Technology"),
    ("ACN",   "Technology"),
    ("FIS",   "Technology"),
    ("FISV",  "Technology"),
    ("CTSH",  "Technology"),
    ("HPE",   "Technology"),
    ("NTAP",  "Technology"),
    ("STX",   "Technology"),
    ("WDC",   "Technology"),
    ("KEYS",  "Technology"),
    ("CDNS",  "Technology"),
    ("SNPS",  "Technology"),
    ("TDY",   "Technology"),
    ("LDOS",  "Technology"),
    ("SAIC",  "Technology"),
    ("BAH",   "Technology"),
    ("ADI",   "Technology"),
    ("ADSK",  "Technology"),
    ("AKAM",  "Technology"),
    ("APH",   "Technology"),
    ("AXON",  "Technology"),
    ("CDW",   "Technology"),
    ("CHKP",  "Technology"),
    ("DDOG",  "Technology"),
    ("DOCU",  "Technology"),
    ("ENTG",  "Technology"),
    ("EPAM",  "Technology"),
    ("FFIV",  "Technology"),
    ("FSLR",  "Technology"),
    ("GDDY",  "Technology"),
    ("GEV",   "Technology"),
    ("GLW",   "Technology"),
    ("GRMN",  "Technology"),
    ("MCHP",  "Technology"),
    ("MPWR",  "Technology"),
    ("MSI",   "Technology"),
    ("NET",   "Technology"),
    ("NTNX",  "Technology"),
    ("NXPI",  "Technology"),
    ("OKTA",  "Technology"),
    ("ON",    "Technology"),
    ("PANW",  "Technology"),
    ("PAYX",  "Technology"),
    ("PLTR",  "Technology"),
    ("ROP",   "Technology"),
    ("S",     "Technology"),
    ("SMCI",  "Technology"),
    ("SNOW",  "Technology"),
    ("SWKS",  "Technology"),
    ("TEL",   "Technology"),
    ("TER",   "Technology"),
    ("TRMB",  "Technology"),
    ("VRSN",  "Technology"),
    ("VRSK",  "Technology"),
    ("WDAY",  "Technology"),
    ("ZBRA",  "Technology"),
    ("ZM",    "Technology"),
    ("ZS",    "Technology"),
    # ── Consumer Discretionary ───────────────────────────────────────────────
    ("AMZN",  "Consumer Discretionary"),
    ("TSLA",  "Consumer Discretionary"),
    ("HD",    "Consumer Discretionary"),
    ("TGT",   "Consumer Discretionary"),
    ("LOW",   "Consumer Discretionary"),
    ("MCD",   "Consumer Discretionary"),
    ("SBUX",  "Consumer Discretionary"),
    ("NKE",   "Consumer Discretionary"),
    ("DIS",   "Consumer Discretionary"),
    ("BKNG",  "Consumer Discretionary"),
    ("UBER",  "Consumer Discretionary"),
    ("ABNB",  "Consumer Discretionary"),
    ("NFLX",  "Consumer Discretionary"),
    ("CMG",   "Consumer Discretionary"),
    ("YUM",   "Consumer Discretionary"),
    ("QSR",   "Consumer Discretionary"),
    ("DPZ",   "Consumer Discretionary"),
    ("EXPE",  "Consumer Discretionary"),
    ("MAR",   "Consumer Discretionary"),
    ("HLT",   "Consumer Discretionary"),
    ("KMX",   "Consumer Discretionary"),
    ("AN",    "Consumer Discretionary"),
    ("BBY",   "Consumer Discretionary"),
    ("ROST",  "Consumer Discretionary"),
    ("TJX",   "Consumer Discretionary"),
    ("ORLY",  "Consumer Discretionary"),
    ("AZO",   "Consumer Discretionary"),
    ("GPC",   "Consumer Discretionary"),
    ("AAP",   "Consumer Discretionary"),
    ("F",     "Consumer Discretionary"),
    ("GM",    "Consumer Discretionary"),
    ("BURL",  "Consumer Discretionary"),
    ("CCL",   "Consumer Discretionary"),
    ("CHWY",  "Consumer Discretionary"),
    ("CPRT",  "Consumer Discretionary"),
    ("CZR",   "Consumer Discretionary"),
    ("DAL",   "Consumer Discretionary"),
    ("DHI",   "Consumer Discretionary"),
    ("DG",    "Consumer Discretionary"),
    ("DLTR",  "Consumer Discretionary"),
    ("DKS",   "Consumer Discretionary"),
    ("EBAY",  "Consumer Discretionary"),
    ("ETSY",  "Consumer Discretionary"),
    ("FL",    "Consumer Discretionary"),
    ("H",     "Consumer Discretionary"),
    ("HAS",   "Consumer Discretionary"),
    ("JBHT",  "Consumer Discretionary"),
    ("LEN",   "Consumer Discretionary"),
    ("LKQ",   "Consumer Discretionary"),
    ("LUV",   "Consumer Discretionary"),
    ("MAT",   "Consumer Discretionary"),
    ("MGM",   "Consumer Discretionary"),
    ("MHK",   "Consumer Discretionary"),
    ("NCLH",  "Consumer Discretionary"),
    ("NVR",   "Consumer Discretionary"),
    ("PAG",   "Consumer Discretionary"),
    ("PENN",  "Consumer Discretionary"),
    ("PHM",   "Consumer Discretionary"),
    ("POOL",  "Consumer Discretionary"),
    ("RCL",   "Consumer Discretionary"),
    ("RL",    "Consumer Discretionary"),
    ("TSCO",  "Consumer Discretionary"),
    ("UAL",   "Consumer Discretionary"),
    ("VFC",   "Consumer Discretionary"),
    ("W",     "Consumer Discretionary"),
    ("WH",    "Consumer Discretionary"),
    ("WHR",   "Consumer Discretionary"),
    ("WSM",   "Consumer Discretionary"),
    ("WYNN",  "Consumer Discretionary"),
    # ── Consumer Staples ────────────────────────────────────────────────────
    ("WMT",   "Consumer Staples"),
    ("COST",  "Consumer Staples"),
    ("KR",    "Consumer Staples"),
    ("PG",    "Consumer Staples"),
    ("KO",    "Consumer Staples"),
    ("PEP",   "Consumer Staples"),
    ("PM",    "Consumer Staples"),
    ("MO",    "Consumer Staples"),
    ("MDLZ",  "Consumer Staples"),
    ("KHC",   "Consumer Staples"),
    ("GIS",   "Consumer Staples"),
    ("CPB",   "Consumer Staples"),
    ("HRL",   "Consumer Staples"),
    ("TSN",   "Consumer Staples"),
    ("SYY",   "Consumer Staples"),
    ("ADM",   "Consumer Staples"),
    ("BG",    "Consumer Staples"),
    ("CLX",   "Consumer Staples"),
    ("CL",    "Consumer Staples"),
    ("KMB",   "Consumer Staples"),
    ("CHD",   "Consumer Staples"),
    ("EL",    "Consumer Staples"),
    ("STZ",   "Consumer Staples"),
    ("BJ",    "Consumer Staples"),
    ("CAG",   "Consumer Staples"),
    ("COTY",  "Consumer Staples"),
    ("FLO",   "Consumer Staples"),
    ("INGR",  "Consumer Staples"),
    ("KDP",   "Consumer Staples"),
    ("MKC",   "Consumer Staples"),
    ("POST",  "Consumer Staples"),
    ("REYN",  "Consumer Staples"),
    ("SFM",   "Consumer Staples"),
    ("SJM",   "Consumer Staples"),
    ("TAP",   "Consumer Staples"),
    # ── Healthcare ──────────────────────────────────────────────────────────
    ("UNH",   "Healthcare"),
    ("CVS",   "Healthcare"),
    ("MCK",   "Healthcare"),
    ("COR",   "Healthcare"),
    ("CAH",   "Healthcare"),
    ("CI",    "Healthcare"),
    ("ELV",   "Healthcare"),
    ("HUM",   "Healthcare"),
    ("CNC",   "Healthcare"),
    ("HCA",   "Healthcare"),
    ("JNJ",   "Healthcare"),
    ("PFE",   "Healthcare"),
    ("MRK",   "Healthcare"),
    ("ABBV",  "Healthcare"),
    ("LLY",   "Healthcare"),
    ("BMY",   "Healthcare"),
    ("AMGN",  "Healthcare"),
    ("GILD",  "Healthcare"),
    ("REGN",  "Healthcare"),
    ("VRTX",  "Healthcare"),
    ("BIIB",  "Healthcare"),
    ("MRNA",  "Healthcare"),
    ("ABT",   "Healthcare"),
    ("TMO",   "Healthcare"),
    ("DHR",   "Healthcare"),
    ("MDT",   "Healthcare"),
    ("SYK",   "Healthcare"),
    ("BSX",   "Healthcare"),
    ("ISRG",  "Healthcare"),
    ("ZTS",   "Healthcare"),
    ("IQV",   "Healthcare"),
    ("A",     "Healthcare"),
    ("BAX",   "Healthcare"),
    ("BDX",   "Healthcare"),
    ("EW",    "Healthcare"),
    ("HOLX",  "Healthcare"),
    ("DXCM",  "Healthcare"),
    ("MTD",   "Healthcare"),
    ("WAT",   "Healthcare"),
    ("RMD",   "Healthcare"),
    ("ALGN",  "Healthcare"),
    ("BIO",   "Healthcare"),
    ("CRL",   "Healthcare"),
    ("COO",   "Healthcare"),
    ("DGX",   "Healthcare"),
    ("DVA",   "Healthcare"),
    ("EXAS",  "Healthcare"),
    ("GEHC",  "Healthcare"),
    ("HSIC",  "Healthcare"),
    ("IDXX",  "Healthcare"),
    ("ILMN",  "Healthcare"),
    ("INCY",  "Healthcare"),
    ("LH",    "Healthcare"),
    ("MOH",   "Healthcare"),
    ("OGN",   "Healthcare"),
    ("PDCO",  "Healthcare"),
    ("PODD",  "Healthcare"),
    ("PRGO",  "Healthcare"),
    ("RVTY",  "Healthcare"),
    ("STE",   "Healthcare"),
    ("TECH",  "Healthcare"),
    ("TFX",   "Healthcare"),
    ("UHS",   "Healthcare"),
    ("UTHR",  "Healthcare"),
    ("VTRS",  "Healthcare"),
    ("XRAY",  "Healthcare"),
    ("ZBH",   "Healthcare"),
    # ── Financials ──────────────────────────────────────────────────────────
    ("JPM",   "Financials"),
    ("BAC",   "Financials"),
    ("WFC",   "Financials"),
    ("GS",    "Financials"),
    ("MS",    "Financials"),
    ("C",     "Financials"),
    ("BLK",   "Financials"),
    ("SCHW",  "Financials"),
    ("AXP",   "Financials"),
    ("BRK-B", "Financials"),
    ("USB",   "Financials"),
    ("TFC",   "Financials"),
    ("PNC",   "Financials"),
    ("COF",   "Financials"),
    ("AIG",   "Financials"),
    ("MET",   "Financials"),
    ("PRU",   "Financials"),
    ("ALL",   "Financials"),
    ("HIG",   "Financials"),
    ("AFL",   "Financials"),
    ("CB",    "Financials"),
    ("MMC",   "Financials"),
    ("AON",   "Financials"),
    ("MA",    "Financials"),
    ("V",     "Financials"),
    ("PYPL",  "Financials"),
    ("SPGI",  "Financials"),
    ("MCO",   "Financials"),
    ("ICE",   "Financials"),
    ("CME",   "Financials"),
    ("MSCI",  "Financials"),
    ("SYF",   "Financials"),
    ("ALLY",  "Financials"),
    ("BK",    "Financials"),
    ("STT",   "Financials"),
    ("NTRS",  "Financials"),
    ("ACGL",  "Financials"),
    ("AMP",   "Financials"),
    ("BEN",   "Financials"),
    ("BRO",   "Financials"),
    ("CBOE",  "Financials"),
    ("CFG",   "Financials"),
    ("CINF",  "Financials"),
    ("CMA",   "Financials"),
    ("EG",    "Financials"),
    ("FAF",   "Financials"),
    ("FHN",   "Financials"),
    ("FITB",  "Financials"),
    ("GL",    "Financials"),
    ("HBAN",  "Financials"),
    ("IBKR",  "Financials"),
    ("IVZ",   "Financials"),
    ("KEY",   "Financials"),
    ("LNC",   "Financials"),
    ("LPLA",  "Financials"),
    ("MKTX",  "Financials"),
    ("MTB",   "Financials"),
    ("NDAQ",  "Financials"),
    ("PFG",   "Financials"),
    ("PGR",   "Financials"),
    ("RF",    "Financials"),
    ("RJF",   "Financials"),
    ("TROW",  "Financials"),
    ("UNM",   "Financials"),
    ("VOYA",  "Financials"),
    ("WRB",   "Financials"),
    ("ZION",  "Financials"),
    # ── Energy ──────────────────────────────────────────────────────────────
    ("XOM",   "Energy"),
    ("CVX",   "Energy"),
    ("COP",   "Energy"),
    ("PSX",   "Energy"),
    ("VLO",   "Energy"),
    ("MPC",   "Energy"),
    ("OXY",   "Energy"),
    ("EOG",   "Energy"),
    ("DVN",   "Energy"),
    ("FANG",  "Energy"),
    ("HAL",   "Energy"),
    ("SLB",   "Energy"),
    ("BKR",   "Energy"),
    ("KMI",   "Energy"),
    ("WMB",   "Energy"),
    ("LNG",   "Energy"),
    ("APA",   "Energy"),
    ("AR",    "Energy"),
    ("CTRA",  "Energy"),
    ("EQT",   "Energy"),
    ("MTDR",  "Energy"),
    ("MUR",   "Energy"),
    ("NRG",   "Energy"),
    ("OKE",   "Energy"),
    ("PR",    "Energy"),
    ("RRC",   "Energy"),
    ("SM",    "Energy"),
    ("TRGP",  "Energy"),
    # ── Industrials ─────────────────────────────────────────────────────────
    ("BA",    "Industrials"),
    ("LMT",   "Industrials"),
    ("RTX",   "Industrials"),
    ("GD",    "Industrials"),
    ("NOC",   "Industrials"),
    ("GE",    "Industrials"),
    ("HON",   "Industrials"),
    ("MMM",   "Industrials"),
    ("CAT",   "Industrials"),
    ("DE",    "Industrials"),
    ("ETN",   "Industrials"),
    ("EMR",   "Industrials"),
    ("PH",    "Industrials"),
    ("IR",    "Industrials"),
    ("FDX",   "Industrials"),
    ("UPS",   "Industrials"),
    ("UNP",   "Industrials"),
    ("CSX",   "Industrials"),
    ("NSC",   "Industrials"),
    ("WAB",   "Industrials"),
    ("TDG",   "Industrials"),
    ("ITW",   "Industrials"),
    ("ROK",   "Industrials"),
    ("SWK",   "Industrials"),
    ("XYL",   "Industrials"),
    ("CARR",  "Industrials"),
    ("OTIS",  "Industrials"),
    ("JCI",   "Industrials"),
    ("FAST",  "Industrials"),
    ("GWW",   "Industrials"),
    ("ACM",   "Industrials"),
    ("ALLE",  "Industrials"),
    ("AME",   "Industrials"),
    ("AOS",   "Industrials"),
    ("APTV",  "Industrials"),
    ("AYI",   "Industrials"),
    ("BLDR",  "Industrials"),
    ("BR",    "Industrials"),
    ("CHRW",  "Industrials"),
    ("CMI",   "Industrials"),
    ("DOV",   "Industrials"),
    ("EFX",   "Industrials"),
    ("EXPD",  "Industrials"),
    ("FLS",   "Industrials"),
    ("GNRC",  "Industrials"),
    ("GXO",   "Industrials"),
    ("HEI",   "Industrials"),
    ("HII",   "Industrials"),
    ("HUBB",  "Industrials"),
    ("J",     "Industrials"),
    ("LHX",   "Industrials"),
    ("LII",   "Industrials"),
    ("MAS",   "Industrials"),
    ("NDSN",  "Industrials"),
    ("NVT",   "Industrials"),
    ("ODFL",  "Industrials"),
    ("PCAR",  "Industrials"),
    ("PWR",   "Industrials"),
    ("ROL",   "Industrials"),
    ("RSG",   "Industrials"),
    ("RXO",   "Industrials"),
    ("SAIA",  "Industrials"),
    ("SNA",   "Industrials"),
    ("TT",    "Industrials"),
    ("TXT",   "Industrials"),
    ("URI",   "Industrials"),
    ("WM",    "Industrials"),
    ("XPO",   "Industrials"),
    # ── Telecom ─────────────────────────────────────────────────────────────
    ("T",     "Telecom"),
    ("VZ",    "Telecom"),
    ("TMUS",  "Telecom"),
    ("CMCSA", "Telecom"),
    ("CHTR",  "Telecom"),
    ("FOXA",  "Telecom"),
    ("NWSA",  "Telecom"),
    ("WBD",   "Telecom"),
    # ── Utilities ───────────────────────────────────────────────────────────
    ("NEE",   "Utilities"),
    ("DUK",   "Utilities"),
    ("SO",    "Utilities"),
    ("D",     "Utilities"),
    ("AEP",   "Utilities"),
    ("EXC",   "Utilities"),
    ("SRE",   "Utilities"),
    ("PCG",   "Utilities"),
    ("XEL",   "Utilities"),
    ("WEC",   "Utilities"),
    ("ES",    "Utilities"),
    ("ED",    "Utilities"),
    ("EIX",   "Utilities"),
    ("AWK",   "Utilities"),
    ("AEE",   "Utilities"),
    ("AES",   "Utilities"),
    ("CNP",   "Utilities"),
    ("CMS",   "Utilities"),
    ("DTE",   "Utilities"),
    ("ETR",   "Utilities"),
    ("EVRG",  "Utilities"),
    ("LNT",   "Utilities"),
    ("NI",    "Utilities"),
    ("OGE",   "Utilities"),
    ("PPL",   "Utilities"),
    ("UGI",   "Utilities"),
    ("VST",   "Utilities"),
    # ── Materials ───────────────────────────────────────────────────────────
    ("LIN",   "Materials"),
    ("APD",   "Materials"),
    ("SHW",   "Materials"),
    ("FCX",   "Materials"),
    ("NEM",   "Materials"),
    ("NUE",   "Materials"),
    ("DOW",   "Materials"),
    ("LYB",   "Materials"),
    ("PPG",   "Materials"),
    ("CF",    "Materials"),
    ("MOS",   "Materials"),
    ("AA",    "Materials"),
    ("CLF",   "Materials"),
    ("ALB",   "Materials"),
    ("AMCR",  "Materials"),
    ("BALL",  "Materials"),
    ("CCK",   "Materials"),
    ("CE",    "Materials"),
    ("DD",    "Materials"),
    ("ECL",   "Materials"),
    ("EMN",   "Materials"),
    ("FMC",   "Materials"),
    ("IFF",   "Materials"),
    ("IP",    "Materials"),
    ("PKG",   "Materials"),
    ("RS",    "Materials"),
    ("SEE",   "Materials"),
    ("SON",   "Materials"),
    # ── Real Estate ─────────────────────────────────────────────────────────
    ("PLD",   "Real Estate"),
    ("AMT",   "Real Estate"),
    ("CCI",   "Real Estate"),
    ("EQIX",  "Real Estate"),
    ("PSA",   "Real Estate"),
    ("SBAC",  "Real Estate"),
    ("EQR",   "Real Estate"),
    ("AVB",   "Real Estate"),
    ("WY",    "Real Estate"),
    ("ARE",   "Real Estate"),
    ("BXP",   "Real Estate"),
    ("CPT",   "Real Estate"),
    ("CSGP",  "Real Estate"),
    ("DLR",   "Real Estate"),
    ("EXR",   "Real Estate"),
    ("FRT",   "Real Estate"),
    ("HST",   "Real Estate"),
    ("IRM",   "Real Estate"),
    ("KIM",   "Real Estate"),
    ("MAA",   "Real Estate"),
    ("O",     "Real Estate"),
    ("SPG",   "Real Estate"),
    ("UDR",   "Real Estate"),
    ("VICI",  "Real Estate"),
    ("WELL",  "Real Estate"),
]

TICKERS:    list[str]        = [t for t, _ in _ALL]
SECTOR_MAP: dict[str, str]   = {t: s for t, s in _ALL}
